<%
'========================================================================================
'Global variable for DBAgebt
'========================================================================================
Dim gTypeCD
Dim gFieldCD
Dim gFieldNM
Dim gFieldLen
Dim gFieldType
Dim gDefaultT
Dim gNextSeq
Dim gKeyTag
Dim gMethodText

Dim gTypeCD1
Dim gFieldCD1
Dim gFieldNM1
Dim gFieldLen1
Dim gFieldType1
Dim gDefaultT1
Dim gNextSeq1
Dim gKeyTag1
Dim gMethodText1

Dim gTypeCD2
Dim gFieldCD2
Dim gFieldNM2
Dim gFieldLen2
Dim gFieldType2
Dim gDefaultT2
Dim gNextSeq2
Dim gKeyTag2
Dim gMethodText2
%>