Dim lgBlnFlgChgValue                                                   '☜: Variable is for Dirty flag
Dim lgIntGrpCount                                                      '☜: Group View Size를 조사할 변수
Dim lgIntFlgMode                                                       '☜: Variable is for Operation Status
Dim lgLngCurRows
Dim lgStrPrevKey
Dim lgStrPrevKeyIndex
Dim lgStrPrevKeyIndex1
Dim lgSortKey
Dim lgCurrentSpd                                                       '☜: "A"(Spread #1) "B"(Spread #2)
Dim lgActiveSpd                                                        '
Dim lgKeyStream
Dim lgF2By2
Dim lgF0
Dim lgF1
Dim lgF2
Dim lgF3
Dim lgF4
Dim lgF5
Dim lgF6
Dim lgUsrIntCd
Dim lgPageNo
Dim lgEBProcessbarOut